rana=input("Whats your frog's name? ")
print()
print("Once upon a time there was a frog named ", rana)
input()
print("one day", rana)
print("woke up and couldnt find his friend pepe")
input()
print ("so", rana)
print("got up and started searching for clues of where his friend could be")
input()
print(rana ,"found pepe's notebook and in this notebook there were two drawings")
input()
print("one drawing was about a forest")
print("and the other was about a city")
input()
print(rana, "decided that he had to look for him in one of this two places ")
input()
print("but he didnt know if he should go to the city or to the forest")
input()
place=input ("where should we go, forest or city? ")

if (place=="forest"):
 print(rana ,"started walking towards the forest ")
 input()
 print("he was very decided of finding his friend Pepe")
 input()
 print("and he wasn't going to give up...")
 input() 
 print("he was walking for more than an hour")
 input()
 print("when suddenly he arrived to one place that got two paths ")
 input()
 print("the one at the left was a way full of flowers with a lot of butterflies")  
 input()
 print("and the one a the right was a way dark with no sun a lot of trees and it was raining ")
 input()
 way=input ("what way shoul we take?") 
 if (way=="left"):
  print(rana ,"decided to go to the left")
  input()
  print("he started to walk ")
  input()
  print("he walked untill he found a very pretty house")
  input()
  print("the house was decorated with pretty flowers and trees and plants")
  input()
  print(rana,"had a feeling that his friend pepe was going to be inside that pretty house")
  input()
  print("because pepe had always talked about how much he loves plants and flowers")
  input()
  print(rana,"aproached the big fancy door")
  input()
  print("but...")
  input()
  print("the door needed a password to be opened")
  input()
  print(rana,"was about to give up when suddenly he found a note pasted into a big red flower")
  input()
  print("the note said:")
  input()
  print("what insect is small, colorful and beautiful and can be seen flying in the sky")
  input()
  riddle=input("whats the answer to this riddle?")
  if(riddle=="butterfly"):
       print(rana,"wrote butterfly on the doorlock and it immediately opened")
  input()
  print(rana,"walked inside the house")
  input()
  print("inside the house there was a lot of rooms")
  input()
  print(rana,"started looking around")
  input()
  print("when suddenly he heard a noise")
  input()
  print("at first he thought it was pepe")
  input()
  print("but when he listened carefuly he realized it was music")
  input()
  print(rana,"looked arround and saw a sign that said...")
  input()
  print("party upstairs")
  input()
  print(rana,"walked upstairs and he started looking through all the doors the house had")
  input()
  print("when he reached the last door at the end of the hallway...")
  input()
  print("he saw it was a only frogs part!!")
  input()
  print("and in between all those frogs he recognized his best friend pepe")
  input()
  print(rana,"screamed...")
  input()
  print("PEPEEEEEEE")
  input()
  print("pepe turned around and they both ran to hug eachother")
  input()
  print(rana,"asked pepe why did he left and why")
  input()
  print("pepe said he'll explain later")
  input()
  print("and the two best friends continued enjoying the party")
 if (way=="rigth"):
  print(rana ,"decided to go to the right")
  print()
  print(rana,"started to walk and he started looking around")
  input()
  print("he was walkig when he found a lake")
  input()
  print("he was looking to find another way to go through ")
  input()
  print("but swimming the lake was the only way ")
  input()
  print("he was getting in the lake when he saw a poster that said:")
  input()
  print("CAUTION COCODRILES!!!")
  input()
  print("when he saw that he got scared ")
  input()
  print("and he almost gave up")
  input()
  print("but he had an idea")
  input()
  print("he dicided to creat a boat")
  input()
  print("he started looking around for things that could work")
  input()
  print(rana,"found sticks, rocks and mud")
  input()
  print(rana,"was finishing the boat when he realised that he was missing the flag")
  input()
  print("he was very sad because he didn't have anithing to make it")
  input()
  print("he saw a tree and decide to climb to look for something")
  input()
  print("when he saw a leaf")
  input()
  print("it was perfect for his boat")
  input()
  print("when he almost got it ")
  input()
  print("he find a bird that was taking care of the tree")
  input()
  print("he tried to be quiet so the bird doesn't see him")
  input()
  print("but the bird saw him and didn't let him take the leaf")
  input()
  print(rana,"talked with the bird and convinced him to let him take the leaf and he will be helping him with something he wants ")
  input()
  print("the bird told him that he can't fly so that he wants to cross with him")
  input()
  print(rana,"accepts and they finis making the boat and they start the adventure ")
  input()
  print("they were crossing the lake when they hear a sound")
  input()
  print("they start looking around")
  input()
  print("when they saw something ")
  input()
  print("there was something moving in the water")
  input()
  print("it was a cocodrile ")
  input()
  print("they get really scared and they jump out of the boat")
  input()
  print("they get into a hole")
  input()
  print("they didn't know were they were")
  input()
  print("and they were really scared")
  input()
  print("they didnt know what to do")
  input()
  print("so they decided to wait until the sun rises ")
  input()
  print("they hug and try to sleep...")
  input()
  print("when they wake up they were all wet and they can see the way out")
  input()
  print("when they get out")
  input()
  print("they didn't know were they were")
  input()
  print("there were a lot of flowers")
  input()
  print("but they look kind of suspicious")
  input()
  print("they desided to cross the flowers")
  input()
  print("and in one moment they lost each other")
  input()
  print(rana, "was really scared")
  input()
  print(rana,"start to shout to bird to find him ")
  input()
  print("but he was not answering ")
  input()
  print(rana,"decided to continue his way without him")
  input()
  print(rana,"start walking when he find a compass")
  input()
  print("he decided to take it ")
  input()
  print("he saw that it was broken ")
  input()
  print("so he decided to fix it")
  input()
  print("he was walking when he found a little house ")
  input()
  print("he decide to knock the door")
  input()
  print("a little rabbit open the door")
  input()
  print("it invited him to come in")
  input()
  print(rana, "enter ti the house ")
  input()
  print("it was full of clocks ")
  input()
  print("he decided to ask her if she can fix his compass")
  input()
  print("the little rabit said yes ")
  input()
  print("but in exchange  ")
  input()
  print("she asked him to go and get her 3 carrots")
  input()
  print("he accepted and went out looking for them")
  input()
  print("he saw a poster that says carrots 5 kilometrers ")
  input()
  print("he continue walking and find the  carrots ")
  input()
  print("he thought ")
  input()
  print("this is pretty easy")
  input()
  print("he was trying to take a carrot when he saw that there was a house ")
  input()
  print("inside that house there was a tini door")
  input()
  print("made perfectly for a...")
  input()
  print("A FROG!!")
  input()
  print(rana,"walked in the door and he saw a frog")
  input()
  print("he ran towards that frog and realized he was his friend pepe")
  input()
  print("he told pepe everything that had happened and pepe said he would explain everything later")
  input()
  print(rana,"and pepe went and gave the carrots to the bunny ")
  input()
  print("they walked home together and the best friends lived happily together")
"voya poner un while para hacer que la rana escja cual lugar escijer el 3 es el correcto en los otros lo aplastan"
if (place=="city"):
 print(rana ,"started walking to the city ")
 input()
 print( "and he didn't now were to go ")
 input()
 print(rana ,"look's again Pepe's notebook and find out that he had a list of his favorite places of the city ")
 input()
 print("favotite places: dairy queen, mall, chuck e cheese")
input() 
thing=input("where should we go? ")
if (thing=="dairy queen"):
  print(rana ,"start walking to dairy queen")
  input()
  print(rana,"finally got into to dairy queen, he sat down on a chair and started to think")
  input()
  print("he asked for the menu")
  input()
  print("lemon,apple,kiwi,elderberry ")
  input()
  print("he realized that it was a secret message in the icecreams")
  input()
  print("he take the first letter of each ice cream and put it together")
  input()
  password=input("what is the word?")
  if (password=="lake"):
   input()
   print(rana,"decide to go to the lake")
   input()
   print("when he arrive to the lake... ")
   input()
   print("look at me at the biggest rocks")
   print(rana ,"jump up to the rock and finds his frien Pepe")
   input()
   print(rana ,"give him a big hug, and they go back to their home")

if (thing=="mall"):
  print(rana ,"start walking to the mall ")
  input()
  print("when",rana)
  print("finally got to the mall, he start to walk trying to finds something")
  input()
  print("he was looking for any kind of clue, when he found some footsteps")
  input()
  print("he decides to follow them")
  print("they take him into a room with 2 doors")
  print("in first door say keep out ")
  print("and in the second it say is it safe?")
  input()
 
  door=input ("wich door are you entering?")
input()

if (place=="first door"):
  print(rana ,"walk in to the door and he die")
  print("GAME OVER")

if (place=="second door"):
  print(rana ,"walk in to the door and find his friend pepe ")
  print("he give him a big hug")
  print("pepe: you find me! great job")
  print("...")
  print(rana,"asked Why you are here??")
  print("Pepe: Because i am working here :DD")
  print("they go out of the room and go back home")
if (thing=="chuck e cheese "):
  input()
  print(rana,"arrived and he was very sad because he couldnt find Pepe")
  input()
print("so he decided to order a pizza")
input()
print("When the waitress came to you, she recognized you and told you that she had seen Pepe on the other side of the city")
print(rana,"begins his adventure")
input()
print("later you meet someone very suspicious in a all")
input()
print("the mysterious person never told you his name, but he mentioned that he might know where Pepe is")
print("BUT... you never told him anything about Pepe, so how did he know his name?")
input()
print("the mysterious person invites you to dinner, he starts asking you some questions about Pepe")
input()
while True:
  print("How many drawings are in the Pepe's notebook? ") 
  R1=int(input())
  print("What animal is Pepe? a)Frog  b)Elefant c)Rat")
  R2=input()
  
  if(R1==2 and R2=="a"):
    print("VERY GOOD!!")
    break 
  else:
    print("TRY AGAIN")
print("Mysterious Person: You know all about Pepe")
print(rana,":Of course, I'm Pepe's best friend")
print("Mysterios Person: As a reward, you know my identity...I am Pepe")
print(rana,"said: OMG,but how? ")
input()
input()
print(rana,"was shoked")
input()
print(rana,"couldt understand why pepe changed his identity ")
input()
print(rana,"asked pepe for an explanation ")
input()
print("pepe said he was working with the government ")
input()
print("and there were bad people looking for him")
input()
print("pepe said he had ran away to keep his best friend safe from danger")
input ()
print("pepe couldn't explain more and take rana to a safe place ")
input ()
print(rana,"was shoked ")
iput()
print(rana,"said: so how are we returning home?")
inout()
print("pepe: we have to make a plan")
input()
print("the goverment was looking fore pepe and wanted to kill him")
input()
print(rana,"said: i dont have any ideas of what can we do")
input()
print("pepe: we have only 24 hours to get back home")
input()
print("pepe: i have two ideas")
input()
print(rana,"i hear you")
input()
print("pepe: the fisrt one is wait until tomorrow and take a boat")
input()
print("pepe: and the second is going to the store to buy new clothes ")
input()
print(rana,"said: i prefer the second one") 
print(rana,"said: and what are we going to do with the clothe?")
input()
print("we are going to camuflaje with the other citizens ")
input()
print(rana,"was not convinced ")
input()
print("but he accepted ")
input()
print("they go to the store and buy some normal clothes  ")
input()
print(rana,"went to the bus stop and bought a two tickets to go back home")
input()
print("it was all going perfect ")
input()
print("they get into the bus and start the trabel ")
input()
print("they were about to arrived ")
input()
print("wen pepe stop the bus and get down ")
input()
print(rana,"didn't understand why did pepe do that but he follow him")
input()
print(rana,"said: WHAT HAPPEN?")
input()
print("pepe: they were people of the government in the bus")
print("we will have to continue walking")
input()
print("the bus stop and the government people get down")
input()
print("pepe: but now we have to run")
input()
print(rana,"and pepe start runing into a flower field ")
input()
print("they lost the government")
input()
print("they were really tired ")
input()
print("and they desided to take a break ")
input()
print("they lay down in the flowers")
input()
print("pepe: did you remember when we first meet?")
input()
print(rana,"said: why?")
input()
print("pepe:eemmmmm")
input()
print("pepe: what I'm trying to say is that ")
print("pepe: i feel something fore you ")
input()
print(rana,"ohh i don't kniw what to say")
input()
print("pepe: you dont have to say anything ")
input()
print("pepe: well i will try ti sleep ")
input()
print("pepe: good night ")
input()
print(rana,"and pepe get back home")
input()
print("when they enter the house ")
print(rana,"did something that he wanted to do many years ago")
input()
print(rana,"kiss pepe")
print(rana,"said: i like you too pepe ")
input()
print("and they live happy for ever ")
input()
print("THE END")